package H.utility;
// Generated 28-Feb-2012 11:39:42 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Teams generated by hbm2java
 */
public class Teams  implements java.io.Serializable {


     private Integer teamid;
     private String name;
     private Integer active;
     private Set userses = new HashSet(0);

    public Teams() {
    }

    public Teams(String name, Integer active, Set userses) {
       this.name = name;
       this.active = active;
       this.userses = userses;
    }
   
    public Integer getTeamId() {
        return this.teamid;
    }
    
    public void setTeamId(Integer teamId) {
        this.teamid = teamId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getActive() {
        return this.active;
    }
    
    public void setActive(Integer active) {
        this.active = active;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }




}


